### ISSUE TITLE
The code block displays an exception

### ISSUE THREAD

**Issue by wanyt** [klugjo/hexo-theme-alpha-dust#11]
I put a class into the block about a hundred lines, and it shows several blank lines, I don't know why would this happened, This is the picture link:  http://oc3k2hfgm.bkt.clouddn.com/%E6%8D%95%E8%8E%B7.PNG

**Comment by klugjo** [comment]
I thought this issue was fixed. Do you have the latest version ?

It was fixed in https://github.com/klugjo/hexo-theme-alpha-dust/commit/179b439baefcd1488bdc3bc49f9342465a41dd73

**Comment by wanyt** [comment]
I'll refresh the version tonight and try again.
