### ISSUE TITLE
If you have deactivated comment, there are always a " KOMMENTARE" tag.

### ISSUE THREAD

**Issue by notlsd** [klugjo/hexo-theme-alpha-dust#12]
Please reference my blog here

https://notlsd.github.io/2017/03/16/BLOG-101-Hello-World/

**Comment by klugjo** [comment]
How did you deactivate the comments ?

Look in the _config.yaml fir the theme if there is something under `disqus_shortname`

**Comment by klugjo** [comment]
That is the condition used to display the text:

```
 <% if (theme.comments && theme.comments.disqus_shortname){ %>
                <a href="<%- item.permalink %>#disqus_thread" class="comments article-comment-link"><%= __('comment') %></a>
<% } %>
```

https://github.com/klugjo/hexo-theme-alpha-dust/blob/master/layout/_partial/article-short.ejs

**Comment by klugjo** [comment]
Yes there is a bug sorry. I will fix it during this weekend.

Thanks for using the theme :)

**Comment by notlsd** [comment]
Cool theme ~

Thanks : )

**Comment by klugjo** [comment]
Fixed. The latest version should fix your problem. Thanks
