### ISSUE TITLE
Footnote cannot be diplayed

### ISSUE THREAD

**Issue by notlsd** [klugjo/hexo-theme-alpha-dust#14]
May reference this essay 

<https://notlsd.github.io/2017/03/22/Snows-of-Kilimanjaro/> 

There should be four footnote, as Markdown source code shown here.

` [^1]: \_Dung\_动物粪便 `

` [^2]: \_Drunkard\_酒鬼 `

` [^3]: \_Sportif\_运动狂 `

` [^4]: \_Dread_惧怕 `

**Comment by klugjo** [comment]
Markdown doesn't support footnotes, but you can manually fake it¹ with Unicode characters or superscript tags, e.g. <sup>1</sup>
