### ISSUE TITLE
Install/Setup to github repo. hosted website

### ISSUE THREAD

**Issue by legendarynacar** [klugjo/hexo-theme-alpha-dust#16]
Hi. I want to use your theme for my github hosted website but I could not figure out how to do. I copied to my repository and modified _config.yml but I guess github searchs index.html(.php what so) on root folder. So how can I modify it for github.

**Comment by klugjo** [comment]
Hi,

I am not sure where you are stuck,

here are the steps

- get the hexo site to work on your local environment with `hexo server`
- get the site to generate properly `hexo generate`
- push the content of public to your github.io repo using standard git commands

And that should be enough

**Comment by legendarynacar** [comment]
I think it is my fault. I could not thing to create a local and install hexo. I will try that.

**Comment by klugjo** [comment]
yes you can follow the steps on https://hexo.io/ to get started

Closing this ticket as not related to my theme. But you can still comment and I will help if I can 

Good luck
