### ISSUE TITLE
Multi Thema install

### ISSUE THREAD

**Issue by legendarynacar** [klugjo/hexo-theme-alpha-dust#17]
Yoo, 

I am trying to configure multi themes website on github as you know. I will only use hexo themes , and just a few like 2-3.

I think, it could be done with theme in theme.

- Main Theme (/)
	- Theme 1 (/Science)
	- Theme 2 (/Cyber)
	- Theme 3 (/Life)
	- MainTheme (/Contact)
	- MainTheme (/AboutMe)

Do you think, is it possible?

**Comment by klugjo** [comment]
Hi,

No this is not supported by Hexo by default.

But you should go ask your questions on the hexo project
