### ISSUE TITLE
Improvement : Add some independent category page ?

### ISSUE THREAD

**Issue by notlsd** [klugjo/hexo-theme-alpha-dust#19]
An independent category page makes much more clear post management.

Example 

https://bitmingw.github.io/categories/index.html

**Comment by klugjo** [comment]
I have added a tags and categories index to the site. Check it out

Demo: http://www.codeblocq.com/assets/projects/hexo-theme-alpha-dust/

Docs:

https://github.com/klugjo/hexo-theme-alpha-dust#tags-page
