### ISSUE TITLE
How to show LaTeX in post?

### ISSUE THREAD

**Issue by okcd00** [klugjo/hexo-theme-alpha-dust#22]
I installed `hexo-renderer-marked` for showing LaTeX in my article, but it doesn't show up on `alpha-dust`.

![image](https://user-images.githubusercontent.com/9395067/30626282-56ca375c-9dfb-11e7-9cfa-f3e24ae4c2ec.png)

I thought maybe there's something wrong with my code, but when I change theme to `next` it works.
![image](https://user-images.githubusercontent.com/9395067/30626373-f7d11756-9dfb-11e7-8596-c8cf4c328632.png)

I love your theme very much! Hope for helping or adding support with LaTeX in `alpha-dust`.^_^

**Comment by klugjo** [comment]
LaTeX is not supported by default. I am not sure about `hexo-renderer-marked` supporting LaTeX. Maybe you could ask on that project's page.

Otherwise you can maybe have a look at 3rd party library and add it to the theme

**Comment by okcd00** [comment]
Thanks for your reply, I'll try 3rd party library for it.

**Comment by klugjo** [comment]
Thanks. LaTeX support is not standard to hexo and probably something that Next added as a bonus. I will try to implement it as well when I can find the time. But if you are in a rush, best to implement it yourself

Sorry for the inconvenience

**Comment by okcd00** [comment]
Thanks a lot ^_^
I love this theme so much for its **cool** sence and so easy to use, and really thanks for your kindness. 
P.S. looking forward to your new works~

**Comment by okcd00** [comment]
**LaTeX support done,** and I think it feels nice to share.
Write a `mathjax.ejs` in `layout/_partial/`, then modify `layout/article_long.ejs` here:
```
<div class="content">

        <!-- Gallery -->
        <% if (item.photos && item.photos.length){ %>
            <%- partial('gallery') %>
        <% } %>

		<!-- MathJax support -->
		<%- partial('_partial/mathjax') %>
		
        <!-- Post Content -->
        <%- item.content %>
    </div>
```

After that, update `em` and `escape` in your `inline.js`(for kramed) or `marked.js`(for marked)
```
//escape: /^\\([\\`*{}\[\]()#$+\-.!_>])/,
  escape: /^\\([`*\[\]()#$+\-.!_>])/,
//em: /^\b_((?:__|[\s\S])+?)_\b|^\*((?:\*\*|[\s\S])+?)\*(?!\*)/,
  em: /^\*((?:\*\*|[\s\S])+?)\*(?!\*)/,
```

![image](https://user-images.githubusercontent.com/9395067/30908621-c41b6424-a3b0-11e7-898d-7c83eef42af5.png)

you can also see effects in [this article](https://okcd00.github.io/articles/2017-09/【O2OTM】你的搜索透露了你的喜好——跨模态推荐.html), sorry for written in Chinese, just focus on LaTeX :)

**Comment by klugjo** [comment]
Thanks for sharing. Will check it out
