### ISSUE TITLE
Duplicate page title for single pages

### ISSUE THREAD

**Issue by DreadBoy** [klugjo/hexo-theme-alpha-dust#23]
I created new page with `hexo new page "test"` and when I open it, page has duplicate title. First title comes from header that is same for all pages and second title comes from page's info, together with date. I find this very odd... is this desired behaviour?

**Comment by klugjo** [comment]
No I don't think that is the expected behaviour.

Is there a live example ? Can you paste the front matter (meta information) of your post ?

**Comment by DreadBoy** [comment]
Live example: 
>   http://vozzel.games/test/

Front matter:
```
---
title: test
date: 2017-10-29 12:15:38
---
```
First title comes from [page's template](https://github.com/klugjo/hexo-theme-alpha-dust/blob/master/layout/page.ejs#L5) and second from [article's template](https://github.com/klugjo/hexo-theme-alpha-dust/blob/master/layout/_partial/article-long.ejs#L7).

I created new partial template for page, anyway, because I don't need meta info displayed below page's title so I'm not waiting for a fix, just telling you that there might be a bug in theme. ;)

**Comment by klugjo** [comment]
Fixed: https://github.com/klugjo/hexo-theme-alpha-dust/commit/dc023fd81e6ef054c86fddb7781e2554e134cfb5

I got it now. Good catch mate and thanks for reporting :)
