### ISSUE TITLE
How to add "Categories" to the bottom of the page?

### ISSUE THREAD

**Issue by sp4c** [klugjo/hexo-theme-alpha-dust#24]
Hello developer,your themes is so **coooool**,and i want to know how to add "Categories" to the bottom of the page just like your demo page .
![qq 20171105112450](https://user-images.githubusercontent.com/33349032/32411649-3714518c-c21c-11e7-98ff-891b99cd8919.png)
And why not to add a function named "Frinedlyship Links",between the "About" and "Rencent Post",i think it's also someone need :)

**Comment by klugjo** [comment]
1) To display the categories section you need to have at least on post with a category set up.

2) To change the footer layout, you need to modify 

https://github.com/klugjo/hexo-theme-alpha-dust/blob/master/layout/_partial/footer.ejs

**Comment by sp4c** [comment]
It works.Thanks so much.:)
