### ISSUE TITLE
Can't set post icon in front matter

### ISSUE THREAD

**Issue by DreadBoy** [klugjo/hexo-theme-alpha-dust#26]
It seems like theme allows customisation of logo for each post or page but there's a bug. Variables set in front matter should accessed with `page.logoIcon` but theme tries to access it with `logoIcon`. If I correctly identified a problem, please accept PR #25.

**Comment by klugjo** [comment]
Where did you see that the theme allows the customisation of the logo for each post ? To be fair I have built this theme more than a year ago an I don't quite remember.

I can't see anything in the doc.

The condition you see is to change the icon for categories and tags pages

https://github.com/klugjo/hexo-theme-alpha-dust/blob/master/layout/page.ejs#L5

Can you make sure that these still works as expected and add the info about logoIcon to the README ?

**Comment by DreadBoy** [comment]
I misunderstood that code, you are right.

Since I can change global icon, I expected to be able to set different icon for separate posts but this feature simply wasn't implemented. I closed PR #25 because it would cause regression and instead propose #27. It will allow overriding default icon with post specific icon in front matter like this:

```˙
---
title: Post title
date: 2017-11-20 15:04:15
logoIcon: fa-pencil-square
---
```

**Comment by klugjo** [comment]
Thanks almost there :)

Can you add the same for single pages (like about page for example ?)

https://github.com/klugjo/hexo-theme-alpha-dust/blob/master/layout/page.ejs#L20

**Comment by DreadBoy** [comment]
What about tags and categories, should users also be able to override those? I would say yes...

**Comment by klugjo** [comment]
yes let's do that. override the tags and cat.

**Comment by DreadBoy** [comment]
Great. I also included new feature in README.

**Comment by klugjo** [comment]
Thanks a lot :)

Fixed by https://github.com/klugjo/hexo-theme-alpha-dust/pull/27
