### ISSUE TITLE
Doesn't this theme support search?

### ISSUE THREAD

**Issue by xnervwang** [klugjo/hexo-theme-alpha-dust#28]
Hi guys,

How about adding a search textbox? Without search it's not easy to find a post.

**Comment by klugjo** [comment]
Good idea. Sorry I have been busy travelling and starting a new job. Will look into it when i have time

**Comment by SimonHu-HN** [comment]
Agree. Equiping search textbox will make the 'alpha-dust' more beautiful. :smirk:

**Comment by xnervwang** [comment]
2 year later...

**Comment by klugjo** [comment]
Hi, unfortunately this is not supported by hexo by default.

Some JavaScript hacking is required. Why don't one of you have a look ?
