### ISSUE TITLE
About and Tag Page

### ISSUE THREAD

**Issue by wanyt** [klugjo/hexo-theme-alpha-dust#3]
I want to create a Tag page like the Archives, that there is a list show all the tags, and there is another page list all the articles about that tag when I click the item in the list. What's more, I hope the word "Tags" below the icon, but not on the place of an article title that is surround with square brackets. On the About page, too. I want to know how to deal with this.

**Comment by klugjo** [comment]
This feature is not supported by hexo unfortunately.

You can create the page manually by creating a custom page and keeping an up to date list of tages and links

Sorry for that .....

**Comment by klugjo** [comment]
I have added a tags and categories index to the site. Check it out

Demo: http://www.codeblocq.com/assets/projects/hexo-theme-alpha-dust/

Docs:

https://github.com/klugjo/hexo-theme-alpha-dust#tags-page
