### ISSUE TITLE
the menu icon didn't show, how can I do?

### ISSUE THREAD

**Issue by Student-HXJ** [klugjo/hexo-theme-alpha-dust#31]
Hi, I am updated font awesome to the version of 5.7.2, then my menu icon didn't show normally. it just becomes square now. So how can I do to solve this problem?

**Comment by klugjo** [comment]
Do you have a link to your site ? Can you check the icon name corresponds ?

**Comment by klugjo** [comment]
I just checked and the hex value is the same in the latest font awesome
https://fontawesome.com/icons/bars?style=solid

**Comment by klugjo** [comment]
This is the place where the icon is set:

https://github.com/klugjo/hexo-theme-alpha-dust/blob/master/source/css/_partial/menu.styl

**Comment by Student-HXJ** [comment]
Sorry I just check the issue, and I have already solved my problem 

<nav>
    <a <i class="fas fa-bars"></i></a>
</nav>
And this is my solution.
