### ISSUE TITLE
How to turn the menu items into Chinese by default?

### ISSUE THREAD

**Issue by ckx516712534** [klugjo/hexo-theme-alpha-dust#34]
When I generated new post/page, the menu items were always English. I looked over your source code and still don't get it how.
Quite troubling when I translated them one by one every time... TAT

**Comment by ckx516712534** [comment]
[https://ckx516712534.github.io/](url) here's my blog

**Comment by ckx516712534** [comment]
here's my blog.
https://ckx516712534.github.io/
And I don't think the comment function works?

**Comment by ckx516712534** [comment]
I tried to define them in the language file.But it still doesn't work.
![微信截图_20190725170124](https://user-images.githubusercontent.com/18141218/61861220-fad91380-aefd-11e9-9ab2-a20f2b312034.png)

**Comment by klugjo** [comment]
You have to change it in _config.yml

```
menu:
  text1: link1
  text2: link2
```

**Comment by ckx516712534** [comment]
Oh god thank u so much! I love this theme.
