### ISSUE TITLE
What format to fill in "email_url:"？

### ISSUE THREAD

**Issue by CSGrandeur** [klugjo/hexo-theme-alpha-dust#5]
I tried : 
\\#xxx@xx.com
xxx@xx.com
\\xxx@xx.com
/xxx@xx.com

all will be converted as:  webroot/......@xx.com

**Comment by klugjo** [comment]
Will have a look

**Comment by klugjo** [comment]
This is now fixed. Please pull the latest version. Thank for reporting the bug !
