### ISSUE TITLE
Code blocks with blank lines not showing up correctly

### ISSUE THREAD

**Issue by 4-20ma** [klugjo/hexo-theme-alpha-dust#6]
When I have a code block with blank lines, it is rendered incorrectly using the `alpha-dust` theme (renders correctly with default `landscape` theme). The blank lines are grouped together at the beginning and ending of the code block and the remaining lines are placed together without blanks. I believe this is the same as issue #1.

```
$ node --version
v6.5.0
$ npm --version
3.10.3
$ cd themes/alpha-dust/ && git log -1
commit 03f7dac61889994cb8f302fa56b106b5d5812da6
Author: klugjo <klughertz.j@gmail.com>
Date:   Sun Sep 4 21:36:18 2016 +0800

    FIX: Fix an issue where the link to email in the footer was incorrect
```

Reproduce this issue with a new Hexo site:

```
$ mkdir hexo-test
$ cd hexo-test/
$ hexo init
$ hexo new post
$ $EDITOR source/_posts/post.md
```

File `source/_posts/post.md`:
<pre>
---
title: post
date: 2016-09-18 17:59:38
tags:
---

Code block with blank lines
```
Line 1

Line 3

Line 5

Line 7

Line 9
```
</pre>

```
$ git clone https://github.com/klugjo/hexo-theme-alpha-dust themes/alpha-dust
$ $EDITOR _config.yml
```

File `_config.yml`:
``` yaml
...
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: alpha-dust
...
```

```
$ hexo generate
$ hexo server
```

Renders (incorrect):

Code block with blank lines
```
1
2
3 Line 1
4 Line 3
5 Line 5
6 Line 7
7 Line 9
8
9
```

Change back to `landscape`them by editing file `_config.yml`:
``` yaml
...
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape
...
```

```
$ hexo generate
$ hexo server
```

Renders (correct):

Code block with blank lines
```
1 Line 1
2
3 Line 3
4
5 Line 5
6
7 Line 7
8
9 Line 9
```

**Comment by klugjo** [comment]
Thanks for reporting this bug once more. There was indeed an issue.

Can you try to pull the latest and let me know if my fix is working ?

Thanks

**Comment by 4-20ma** [comment]
@klugjo this resolves the issue in my test case as well as my own site. Thank you for the quick response.

**Comment by klugjo** [comment]
You are welcome. Thanks for using my theme =)
