### ISSUE TITLE
disable comments not working

### ISSUE THREAD

**Issue by michaelhobbs** [klugjo/hexo-theme-alpha-dust#8]
Hi, first off I really like your theme.
I was trying to disable comments today and found the article_long.ejs file is missing the if statement that checks whether comments are turned on/off in the config.
I copied it over from article-short.ejs

/themes/alpha-dust/layout/_partial/article-long.ejs 
            <% if (theme.comments && theme.comments.disqus_shortname){ %>
                <a href="#disqus_thread" class="comments"><%= __('comment') %></a>
            <% } %>

You may want to fix that :-)

**Comment by klugjo** [comment]
Will do ASAP. Thanks for reporting and glad you like the theme :)

**Comment by klugjo** [comment]
Should be fixed. Let me know

Cheers
