### ISSUE TITLE
if picture is too big ,the theme can`t make picture small

### ISSUE THREAD

**Issue by litttlefisher** [klugjo/hexo-theme-alpha-dust#9]
in the index,if a picture is too big , the picture will be outof the screen.please fix it.
thx

**Comment by klugjo** [comment]
Can you fix it and provide pull request ?

Or provide screenshot and source photo

thanks

**Comment by litttlefisher** [comment]
I found a method to fix it. And I am trying to add '<a href>'out of '<img>'

**Comment by klugjo** [comment]
Ok let me know how it goes or I will close this. thx

**Comment by litttlefisher** [comment]
I hope to add some function like duoshuo(comments function in China),the quantity of reading,tagcloud,sticky posts,share function. So many function I need to redevelop because I`m in China.
Please tell me which function has been developed in this theme, I can use directly.

**Comment by klugjo** [comment]
Most are not here so you need to add it yourself. 

Please submit a pull request when done so that others can enjoy as well.
